language: cpp
compiler:
  - clang
os:
  - linux
script: make
before_script:
  - mkdir build
  - cd build
  - cmake ..
addons:
  apt:
    packages:
      - cmake
      - libboost-all-dev
      - libbcurl3
      - libgtest-dev
