language: cpp
compiler:
  - clang
os:
  - linux
script: make
before_script:
  - mkdir build
  - cd build
  - cmake ..
addons:
  apt:
    packages:
      - cmake
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libcurl4-openssl-dev
      - libgtest-dev
before_install:
 - mkdir -p deps/root/lib deps/src
 - ls /usr/src/gtest
 - cp -r /usr/src/gtest deps/src/
 - ls deps/src/gtest
 - cd deps/src/gtest && cmake . -DCMAKE_BUILD_TYPE=RELEASE && make && cp libg* ../../root/lib ; cd -
 - ls deps/root/lib
