language: cpp
compiler:
  - clang
os:
  - linux
script: make
before_script:
  - mkdir build
  - cd build
  - cmake ..
addons:
  apt:
    packages:
      - cmake
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libcurl4-openssl-dev
      - libgtest-dev
before_install:
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
 - ls /usr/local/lib

