language: cpp
dist: trusty
sudo: required
compiler:
  - clang
os:
  - linux
addons:
  apt:
    packages:
      - cmake
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libcurl4-openssl-dev
      - libgtest-dev
before_install:
 - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
 - sudo apt-get update
 - sudo apt-get install --yes cmake
install:
 - mkdir -p deps/root/lib deps/src
 - cp -r /usr/src/gtest deps/src/
 - cd deps/src/gtest && cmake . -DCMAKE_BUILD_TYPE=RELEASE && make && cp libg* ../../root/lib ; cd -
 - ./scripts/deps
before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
script: make test
